/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/

SELECT * FROM gold.dim_customers LIMIT 5;
SELECT * FROM gold.dim_products LIMIT 5;
SELECT * FROM gold.fact_sales LIMIT 5;

-- Total customers by countries
SELECT 
    COUNT(customer_id) AS customer_count, 
    country
FROM gold.dim_customers 
GROUP BY country 
ORDER BY customer_count DESC

-- Total customers by gender
SELECT 
    COUNT(customer_id) AS customer_count, 
    gender
FROM gold.dim_customers 
GROUP BY gender 
ORDER BY customer_count DESC

-- Total products by category
SELECT 
    COUNT(product_id) AS product_count, 
    category
FROM gold.dim_products 
GROUP BY category 
ORDER BY product_count DESC;

-- Total revenue generated by each product category
SELECT 
    p.category,
    SUM(s.sales_amount) AS total_sales
FROM gold.fact_sales s
LEFT JOIN gold.dim_products p
ON p.product_key = s.product_key 
GROUP BY p.category 
ORDER BY total_sales DESC

-- What is the total revenue generated by each customer?
SELECT 
    c.customer_number,
    c.last_name,
    SUM(s.sales_amount) AS total_sales
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c
ON c.customer_key = s.customer_key 
GROUP BY c.customer_number, c.last_name
ORDER BY total_sales DESC

-- What is the distribution of sold items across countries?
SELECT
    c.country,
    SUM(s.quantity) AS quantity_sold
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c
ON c.customer_key = s.customer_key
GROUP BY c.country
ORDER BY quantity_sold DESC

